# Generated by Django 5.2.5 on 2025-09-05 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='chapitre')),
                ('slug', models.SlugField(blank=True, max_length=48, unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='classe')),
                ('slug', models.SlugField(blank=True, max_length=16, unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='cours')),
                ('slug', models.SlugField(blank=True, max_length=48, unique=True, verbose_name='url')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='matière')),
                ('slug', models.SlugField(blank=True, max_length=16, unique=True, verbose_name='url')),
                ('grade', models.ForeignKey(default='DELETED_GRADE', on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.grade')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
