# Generated by Django 5.2.5 on 2025-09-06 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='contributors',
            field=models.ManyToManyField(related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='course',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default='DELETED_GRADE', on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.grade', verbose_name='classe'),
        ),
    ]
