# Generated by Django 5.2.5 on 2025-09-06 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_author_course_contributors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(null=True, verbose_name='numéro de chapitre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
