# Generated by Django 5.2.5 on 2025-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chapter_number_alter_course_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(verbose_name='numéro de chapitre'),
        ),
    ]
