# Generated by Django 5.2.5 on 2025-09-06 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(null=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=48, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='courses.chapter', verbose_name='Chapitre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=48, verbose_name='titre'),
        ),
    ]
