# Generated by Django 5.2.5 on 2025-09-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_content_alter_chapter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publiée'),
        ),
    ]
