# Generated by Django 5.2.5 on 2025-09-04 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='titre')),
                ('content', models.TextField(verbose_name='contenu')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='action effectuer')),
                ('adresse_ip', models.CharField(max_length=39, verbose_name='adresse IP')),
                ('executed_at', models.DateTimeField(auto_now=True, verbose_name="heure d'exécution")),
                ('user', models.ForeignKey(default='USER_DELETED', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='log', related_query_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
