# Generated by Django 5.2.5 on 2025-09-05 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default='USER_DELETED', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='log', related_query_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
