# Generated by Django 5.2.5 on 2025-08-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cgu',
            field=models.BooleanField(default=True, verbose_name="accepter les conditions d'utilisation"),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='received_email',
            field=models.BooleanField(blank=True, default=True, verbose_name="recevoir des emails d'annonces/mise à jour"),
        ),
    ]
