# Generated by Django 5.2.5 on 2025-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinfo_cgu_alter_userinfo_received_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_is_username',
            field=models.BooleanField(default=False, verbose_name='Utiliser le nom comme pseudo'),
        ),
    ]
