# Generated by Django 5.2.5 on 2025-08-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_name_is_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='_expired',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_is_username',
            field=models.BooleanField(default=False, verbose_name='utiliser le nom comme pseudo'),
        ),
    ]
